### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by vadyaov** [vadyaov/21_maze#1]
## Part 1

- [x] Написать класс Maze (данные о стенах) и класс MazeLoader (парсинг из файла)
- [x] Начать писать каркас интерфейса (скорее всего Qt)
- [x] Изучить QGraphicsView, QGraphicsScene, QGraphicsItem, QPen и QBrush, QPainter
- [x] Найти хорошие примеры в документации Qt с отрисовкой чего-либо
- [x] Подумать как правильно считать размеры клеток, учитывая толщину стен (2px) и размер сцены (500x500px)
- [ ] Продумать архитектуру и паттерны, которые могут быть полезны
- [x] Улучшать архитектуру кода, стараться делать более читабельно и логично, разбивать на модули/классы (возможно стоит сделать из класса Ceil структуру, т.к. ее цель быть максимально простой и удобной, и засунуть ее внутрь класса Maze, поскольку она используется только там)
- [x] Разобраться с выравниванием точек по центру (не работает для первых двух точек)
- [x] Сделать нормальный интерфейс, можно добавить вертикальный layout в 1-й столбец gridlayout для кнопок, добавить radiobutton для возможности включения/отключения выравнивания точек по центру
- [x] Закрасить точки start & end заливкой, сделать цвет решения отличным от цвета второй точки
- [x] Попробовать сделать линию решения с закругленными углами (почитать про PainterPath, там должно это быть)
- [x] Сделать поле для вывода информации об ошибках в Window виджете, разобраться как из RenderArea обрабатывать выпадающие исключения и отправлять информацию об ошибках в Window виджет
- [ ] Есть проблема: волновой алгоритм который я написал не является оптимальным: он хорошо работает только для идеальных лабиринтов. Недостаток состоит в том что он распространяет волны с приоритетом вниз и вправо (рекурсия не остановится пока можно двигаться вниз или вправо). Алгоритм всегла находит путь, но не гаранитрует его оптимальность (в неиделаьном лабиринте может существовать путь короче)
- [ ] Рассмотреть алгоритм Дейкстры

## Part 2

- [x] Пещеры
- [x] Вообще не нравится сделанный label, получилась какая то дешевка. Мб сделать обычный LineEdit или TextBrowser с фиксированным размером. А то это реально кринж
- [x] Пещеры и QTimer - работает не очень хорошо. Если во время работы таймера нажать на, например, генерацию пещеры, то симуляция продолжает работать, то есть таймер не останавливается. То же самое при переключении с Auto на Manually. Надо понять, как остановить таймер из других слотов. Как вариант - сделать таймер полем класса, но тогда возникают проблемы "как написать коннект и где его писать, чтобы не было багов".

## Common
- [ ] Makefile rules: dvi, dist
- [ ] google style

**Comment by vadyaov** [comment]
Начал писать

**Comment by vadyaov** [comment]
начал делать интерфейс.
пока что вообще не понимаю как буду рисовать лабиринт, а именно как буду вычислять координаты стенок

ладно я поговорил с даней и уже понимаю все. данил спасибо тебе большое

**Comment by vadyaov** [comment]
Лабиринт рисовать научился.
Теперь надо научиться его генерировать. Нужно использовать алгоритм Эллера.
Сам алгоритм вроде как понятен, перемещаемся вперед - назад по строкам лабиринта и ломаем стеночки в зависимости от разных факторов

Проблема - не понимаю как интегрировать непересекающееся множество в этот алгоритм
То есть если две и более клеточки не разделены стенами, то они находятся в одном множестве.
В общем чета я запутался и заблудился в этих множествах и лабиринтах, попробую завтра

А пока пойду в балдурс гейт побегаю

**Comment by vadyaov** [comment]
Выравнивание по центру не работает из за строчек 160 и 163 в renderarea.cc потому что я там просто не добавил выравнивание.

**Comment by vadyaov** [comment]
сделал какой никакой обрабочик ошибок, сделал слой для кнопочек, не стал делать закругленный путь так как это проблемно и не так уж и нужно

**Comment by vadyaov** [comment]
буду всегда выравнивать точки, не выравнивать их это чушь

**Comment by vadyaov** [comment]
Пещеры парсятся из файла + отрисовываются. Все ок, только в примере клеточки слегка заезжают друг на друга, а у меня нет. Но это всегда можно будет поправить, просто слегка увеличив размер клеточек, не меняя шаг

**Comment by vadyaov** [comment]
Ждем генерацию лабиринта от Ивана + тесты
